# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce62771e174b176f5aa1973c6d5ff8c8621fa0b2d853056e4fc07d7f9e419c258216aa80106de6423827ea661f28d3cc9e9d59770851509630f2a53b9827a922

test:
  secret_key_base: 9ef0316d95caf88c5120cd9cf9f1a3494b582a1b440eb4ef3d9984793324f656a4725beac775f001896884f97f1d1be54e82ac522f677a5b65b8a938b3dcfc7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
